In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [16]:
v = np.array([1, 2, 3])
print(v, type(v))
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
s = np.array(5)
print(f"s: {s}, s.ndim: {s.ndim}, s.shape: {s.shape}")
print(f"v: {v}, v.ndim: {v.ndim}, v.shape: {v.shape}")
print(m, m.ndim, m.shape)



[1 2 3] <class 'numpy.ndarray'>
s: 5, s.ndim: 0, s.shape: ()
v: [1 2 3], v.ndim: 1, v.shape: (3,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] 2 (3, 3)


In [9]:
class Student:

    def __init__(self, name):
        self._name = name
    @property #getter cause name is protected
    def name(self):
        return self._name
    @name.setter
    def name(self, name):
        self._name = name


In [8]:
s1 = Student("John")
s1.name = "osama"

In [ ]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape((3, 2))
print(mat)
mat = vec.reshape((2, 3))
mat

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
vec = np.array([1, 2, 3, 4])
mat = vec.reshape((vec.shape[0], 1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [25]:
vec = np.array([1, 2, 3, 4])
mat = vec[:, None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
def array_reshape(arr, rows: int = -1, cols: int = -1): # we used defaults as -1 because -1 gets the last number of a dimention of a matrix which returns the same shape
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")
    


In [32]:
vec = [1, 2, 3, 4, 5, 6]
array_reshape(vec, 2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
class C:
    x = 3
o1 = C()

In [42]:
# Higher priority overrides the lower one
boolean = np.array([[False, False, 1],
                [True, True, True],
                [True, False, False]])
print(boolean.dtype)
print(boolean, "\n")

mat = np.array([[1, 2, 3], # here data type is int
                [4, 5, 6],
                [7, 8, 9]])
print(mat.dtype)
print(mat, "\n")

mat1 = np.array([[1.5, 2, 3], # this is float which has a higher data type priority than int
                [4, 5, 6],
                [7, 8, 9]])
print(mat1.dtype)
print(mat1, "\n")

mat2 = np.array([[1.4, "2", 3], # this is string which has a higher data type priority than float
                [4, 5, 6],
                [7, 8, 9]])
print(mat2.dtype)
print(mat2, "\n")

mat3 = np.array([[1.4, "2", o1],
                [4, 5, 6],
                [7, 8, 9]])
print(mat3.dtype)
print(mat3, "\n")

int64
[[0 0 1]
 [1 1 1]
 [1 0 0]] 

int64
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

float64
[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]] 

<U32
[['1.4' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']] 

object
[[1.4 '2' <__main__.C object at 0x000001D3B003FB10>]
 [4 5 6]
 [7 8 9]] 



In [43]:
mat2 = np.array([[1.4, "2", 3], # this is string which has a higher data type priority than float
                [4, 5, 6],
                [7, 8, 9]])
fmat = mat.astype(np.float64)
print(fmat.dtype)
fmat

float64


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])